apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "novu.ws.fullname" . }}
  labels:
    app: {{ include "novu.name" . }}
    component: ws
spec:
  replicas: {{ .Values.ws.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "novu.name" . }}
      component: ws
  template:
    metadata:
      labels:
        app: {{ include "novu.name" . }}
        component: ws
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ws
          image: "{{ .Values.ws.image.repository }}:{{ .Values.ws.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ws.image.pullPolicy }}
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: {{ include "novu.fullname" . }}-config
            - secretRef:
                name: {{ include "novu.fullname" . }}-secret
          {{- with .Values.ws.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: "{{ .Values.ws.port }}"
            - name: WS_CONTEXT_PATH
              value: "{{ .Values.ws.contextPath }}"
            {{- if .Values.global.env.redis.enabled }}
            {{- if .Values.global.env.redis.existingSecret }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.env.redis.existingSecret | quote }}
                  key: {{ .Values.global.env.redis.existingSecretPasswordKey | quote }}
            {{- else if .Values.global.env.redis.password }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "novu.fullname" . }}-secret
                  key: REDIS_PASSWORD
            {{- end }}
            {{- else }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "redis.fullname" . }}"
                  key: redis-password
            {{- end }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb.fullname" . }}
                  key: mongodb-root-password
            - name: MONGO_URL
              value: "mongodb://root:$(MONGO_ROOT_PASSWORD)@{{ include "mongodb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ dig "service" "ports" "mongodb" 27017 .Values.mongodb }}/novu"
            {{- else }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "novu.fullname" . }}-secret
                  key: MONGO_URL
            {{- end }}
          resources:
            {{- toYaml .Values.ws.resources | nindent 12 }}
      restartPolicy: Always