apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "novu.api.fullname" . }}
  labels:
    app: {{ include "novu.name" . }}
    component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "novu.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "novu.name" . }}
        component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "novu.fullname" . }}-config
            - secretRef:
                name: {{ include "novu.fullname" . }}-secret
          {{- with .Values.api.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DISABLE_USER_REGISTRATION
              value: "{{ .Values.global.env.disableUserRegistration }}"
            - name: FRONT_BASE_URL
              value: "{{ .Values.global.env.frontBaseUrl }}"
            {{- if .Values.externalRedis.enabled }}
            {{- if .Values.externalRedis.existingSecret }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalRedis.existingSecret | quote }}
                  key: {{ .Values.externalRedis.existingSecretPasswordKey | quote }}
            {{- else if .Values.externalRedis.password }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "novu.fullname" . }}-secret
                  key: REDIS_PASSWORD
            {{- end }}
            {{- else }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "redis.fullname" . }}"
                  key: redis-password
            {{- end }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb.fullname" . }}
                  key: mongodb-root-password
            - name: MONGO_URL
              value: "mongodb://root:$(MONGO_ROOT_PASSWORD)@{{ include "mongodb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ dig "service" "ports" "mongodb" 27017 .Values.mongodb }}/novu"
            {{- else }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "novu.fullname" . }}-secret
                  key: MONGO_URL
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /v1/health-check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health-check
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always