{{- if .Values.api.httpRoute.enabled -}}
{{- $parentName := default (include "novu.fullname" .) .Values.api.httpRoute.parentRef.name -}}
{{- $parentNamespace := default .Release.Namespace .Values.api.httpRoute.parentRef.namespace -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "novu.api.fullname" . }}
  labels:
    {{- include "novu.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ $parentName }}
      namespace: {{ $parentNamespace }}
      {{- if .Values.api.httpRoute.parentRef.sectionName }}
      sectionName: {{ .Values.api.httpRoute.parentRef.sectionName | quote }}
      {{- end }}
  {{- if .Values.api.httpRoute.hostname }}
  hostnames:
    - {{ .Values.api.httpRoute.hostname | quote }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "novu.api.fullname" . }}
          port: {{ .Values.api.port }}
{{- end }}
